// harness.mjs
//
// Minimal support for running the motion checks under Node.
//
// These run against the bundled geometry fixture rather than the live geometry
// API, so they need no services -- `npm run check:motion` works from a cold
// checkout once assets have been fetched.

import { JSDOM } from 'jsdom';
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
export const PROJECT_ROOT = resolve(HERE, '../../../..');

/**
 * Install a DOM.
 *
 * Must run before importing anything that touches d3, since d3-selection binds
 * to the global document at import time.
 */
export function installDom() {
	const dom = new JSDOM('<!doctype html><html><body></body></html>');
	globalThis.window = dom.window;
	globalThis.document = dom.window.document;
	globalThis.SVGElement = dom.window.SVGElement;
	globalThis.Node = dom.window.Node;
	return dom;
}

/** The bundled fixture, which is a recorded response from the geometry API. */
export function loadFixture() {
	const path = resolve(PROJECT_ROOT, 'src/data/sampleGeometry.json');
	return JSON.parse(readFileSync(path, 'utf8'));
}

/** Which geometry ring backs each animation group. */
const RING_FOR_GROUP = {
	days: 'outer',
	weeks: 'inner',
	months: 'intermediate'
};

/** Shape file backing each group, used only to audit the API's own bounds. */
const SHAPE_FILE_FOR_GROUP = {
	days: 'shapeForDays.svg',
	weeks: 'weekShape.svg',
	months: 'petalForMonths.svg'
};

/**
 * Ring inputs in the shape the motion modules expect, minus the selection.
 *
 * Bounds come from the response's `animationGroups`, exactly as the renderer
 * takes them. This used to be a hardcoded table of shape extents standing in
 * for the `getBBox()` jsdom cannot provide, and it was wrong twice: once
 * claiming the week pivot was 10 when it is 17.945, and once pointing at
 * `inner-week-petal` when the week ring actually places `week-shape` -- a shape
 * twice the real height. Both were client-side guesses about geometry the
 * generator owns, which is the reason the contract now carries them.
 */
export function fixtureRings(api) {
	const sort = (p) => [...p].sort((a, b) => a.angle - b.angle);

	return Object.entries(RING_FOR_GROUP)
		.map(([id, ringKey]) => ({ id, ring: api.geometry.rings[ringKey] }))
		.filter(({ ring }) => ring && ring.placements)
		.map(({ id, ring }) => {
			const bounds = api.animationGroups?.[id]?.bounds;
			return {
				id,
				placements: sort(ring.placements),
				// Left undefined when the response predates the contract, so the
				// fallback path is exercised rather than papered over.
				pivotY: bounds ? bounds.y + bounds.height : undefined,
				shapeExtent: bounds ? bounds.height : undefined
			};
		});
}

/**
 * Audit the bounds the API sent against the shapes it derives them from.
 *
 * The generator computes bounds from each shape module's centering transform
 * rather than measuring, so this catches that derivation going wrong -- a
 * redrawn shape, or a group pointed at the wrong shapeId.
 *
 * Skipped when assets are absent: they are generated by `fetch-assets` and
 * gitignored, so a fresh checkout will not have them yet.
 */
export function assertBoundsMatchShapes(api, fail) {
	const groups = api.animationGroups;
	if (!groups) return 'skipped (response predates the animation contract)';

	const dir = resolve(PROJECT_ROOT, 'src/mandala/assets/shapes');
	if (!existsSync(dir)) return 'skipped (assets not fetched)';

	let checked = 0;
	for (const [id, file] of Object.entries(SHAPE_FILE_FOR_GROUP)) {
		const bounds = groups[id]?.bounds;
		if (!bounds) {
			fail(`${id}: response declares no bounds`);
			continue;
		}
		const path = resolve(dir, file);
		if (!existsSync(path)) continue;

		const match = /viewBox="[\d.\-]+\s+[\d.\-]+\s+([\d.]+)\s+([\d.]+)"/.exec(
			readFileSync(path, 'utf8')
		);
		if (!match) continue;
		checked += 1;

		const [width, height] = [Number(match[1]), Number(match[2])];
		if (Math.abs(bounds.height - height) > 0.01 || Math.abs(bounds.width - width) > 0.01) {
			fail(
				`${id}: API sent ${bounds.width}x${bounds.height} but ${file} is ${width}x${height}`
			);
		}
		// Shapes are centred on their own origin, so bounds straddle it.
		if (Math.abs(bounds.y + height / 2) > 0.01) {
			fail(`${id}: bounds.y ${bounds.y} is not -height/2 — shape is not centred as assumed`);
		}
	}
	return `${checked} group(s) audited against their SVGs`;
}

/** Parse an SVG transform string into a 2x3 matrix, so emitted output is tested. */
export function parseTransform(str) {
	const mul = (a, b) => [
		a[0] * b[0] + a[2] * b[1], a[1] * b[0] + a[3] * b[1],
		a[0] * b[2] + a[2] * b[3], a[1] * b[2] + a[3] * b[3],
		a[0] * b[4] + a[2] * b[5] + a[4], a[1] * b[4] + a[3] * b[5] + a[5]
	];
	let m = [1, 0, 0, 1, 0, 0];
	const re = /(translate|rotate|scale|skewX|skewY)\(([^)]*)\)/g;
	let g;
	while ((g = re.exec(str))) {
		const n = g[2].split(/[\s,]+/).filter(Boolean).map(Number);
		if (g[1] === 'translate') m = mul(m, [1, 0, 0, 1, n[0], n[1] || 0]);
		else if (g[1] === 'scale') m = mul(m, [n[0], 0, 0, n.length > 1 ? n[1] : n[0], 0, 0]);
		else if (g[1] === 'skewY') m = mul(m, [1, Math.tan((n[0] * Math.PI) / 180), 0, 1, 0, 0]);
		else if (g[1] === 'skewX') m = mul(m, [1, 0, Math.tan((n[0] * Math.PI) / 180), 1, 0, 0]);
		else {
			const a = (n[0] * Math.PI) / 180;
			m = mul(m, [Math.cos(a), Math.sin(a), -Math.sin(a), Math.cos(a), 0, 0]);
		}
	}
	return m;
}

export const applyTransform = (m, x, y) => [
	m[0] * x + m[2] * y + m[4],
	m[1] * x + m[3] * y + m[5]
];

export const radiusOf = (p) => Math.hypot(p[0], p[1]);

/** The plain resting form the static renderer writes, with no fold terms. */
export const PLAIN_TRANSFORM = /^translate\([^)]*\) rotate\([^)]*\) scale\([^)]*\)$/;

/**
 * Capture the interpolators d3 will actually run.
 *
 * The alternative -- recomputing the timing in the check -- was how a real bug
 * slipped through: a check that reimplements the thing it is testing agrees
 * with itself no matter what the shipped code does.
 */
export async function captureTweens(d3, play, rings, options) {
	const captured = [];
	const realTransition = d3.selection.prototype.transition;

	d3.selection.prototype.transition = function (...args) {
		const tr = realTransition.apply(this, args);
		const realAttrTween = tr.attrTween.bind(tr);
		tr.attrTween = function (name, factory) {
			if (name === 'transform') {
				this.each(function (d, i) {
					captured.push(factory.call(this, d, i));
				});
			}
			return realAttrTween(name, factory);
		};
		return tr;
	};

	try {
		play(rings, options);
	} finally {
		d3.selection.prototype.transition = realTransition;
	}
	return captured;
}
