#!/usr/bin/env node

/**
 * Fetches shared mandala assets (SVGs, fonts, styles, themes) into src/mandala/assets/.
 *
 * Modes (set via ASSETS_SOURCE env var):
 *   local  — copies from sibling repo ../mandala-generator/my-assets/
 *   s3     — downloads from S3 bucket (default, used in CI)
 */

import { existsSync, mkdirSync, cpSync, readdirSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");

const DEST = resolve(projectRoot, "src/mandala/assets");
const LOCAL_SOURCE = resolve(projectRoot, "../mandala-generator/my-assets");

// ── S3 config (fill these in when ready) ──
const S3_BUCKET = process.env.ASSETS_S3_BUCKET || "YOUR_BUCKET_NAME";
const S3_PREFIX = process.env.ASSETS_S3_PREFIX || "mandala-assets/";
const S3_REGION = process.env.ASSETS_S3_REGION || "us-east-1";

const mode = (process.env.ASSETS_SOURCE || "s3").toLowerCase();

function ensureDir(dir) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

function fetchLocal() {
  if (!existsSync(LOCAL_SOURCE)) {
    console.error(
      `\n  ✗ Local assets not found at ${LOCAL_SOURCE}` +
        `\n    Make sure mandala-generator is cloned as a sibling directory.\n`
    );
    process.exit(1);
  }

  ensureDir(DEST);
  cpSync(LOCAL_SOURCE, DEST, { recursive: true });

  const count = readdirSync(DEST, { recursive: true }).length;
  console.log(`  ✓ Copied ${count} asset(s) from local source → ${DEST}`);
}

function fetchS3() {
  if (S3_BUCKET === "YOUR_BUCKET_NAME") {
    console.error(
      `\n  ✗ S3 not configured. Set ASSETS_S3_BUCKET or use ASSETS_SOURCE=local.\n`
    );
    process.exit(1);
  }

  ensureDir(DEST);

  const s3Uri = `s3://${S3_BUCKET}/${S3_PREFIX}`;
  console.log(`  Syncing from ${s3Uri} (region: ${S3_REGION})…`);

  try {
    execSync(
      `aws s3 sync "${s3Uri}" "${DEST}" --region "${S3_REGION}" --delete`,
      { stdio: "inherit" }
    );
    console.log(`  ✓ Assets synced from S3 → ${DEST}`);
  } catch {
    console.error(`\n  ✗ S3 sync failed. Is the AWS CLI installed and configured?\n`);
    process.exit(1);
  }
}

// ── Shape defs rebuild ──

const SHAPE_DEFS_OUT = resolve(projectRoot, "src/mandala/renderer/shapeDefs.js");
const SHAPES_DIR = resolve(DEST, "shapes");

// Map of shapeDefs key → { file, export, addId }
const SHAPE_SOURCES = [
  { key: "day-shape", file: "shapeForDays.js", export: "dayShape" },
  { key: "week-shape", file: "weekShape.js", export: "weekShape" },
  { key: "inner-week-petal", file: "innerWeekPetal.js", export: "innerWeekPetal" },
  { key: "inner-week-petal-outside", file: "innerWeekPetal.js", export: "innerWeekPetalOutside" },
  { key: "inner-week-petal-inside", file: "innerWeekPetal.js", export: "innerWeekPetalInside" },
  { key: "month-petal", file: "petalForMonths.js", export: "monthPetal" },
  { key: "woman-stretching", file: "womanStretching.js", export: "womanStretching" },
  { key: "man-stretching", file: "manStretching.js", export: "manStretching" },
];

async function rebuildShapeDefs() {
  const shapes = {};

  for (const src of SHAPE_SOURCES) {
    const filePath = resolve(SHAPES_DIR, src.file);
    if (!existsSync(filePath)) {
      console.warn(`  ⚠ Shape file not found: ${src.file}, skipping ${src.key}`);
      continue;
    }
    const mod = await import(filePath);
    let svg = mod[src.export];
    if (!svg) {
      console.warn(`  ⚠ Export "${src.export}" not found in ${src.file}, skipping ${src.key}`);
      continue;
    }
    // Ensure the root <g> has an id attribute for <use href="#...">
    if (!svg.includes(`id="${src.key}"`)) {
      svg = svg.replace(/^(<g\s)/, `$1id="${src.key}" `);
    }
    shapes[src.key] = svg;
  }

  // Build figureShapeMap from figureShapes.js if available
  const figureShapesPath = resolve(SHAPES_DIR, "figureShapes.js");
  let figureMapEntries = `\t'woman stretching': 'woman-stretching',\n\t'man stretching': 'man-stretching'`;
  if (existsSync(figureShapesPath)) {
    const figMod = await import(figureShapesPath);
    if (figMod.figureShapes) {
      figureMapEntries = Object.keys(figMod.figureShapes)
        .map(name => `\t'${name}': '${name.replace(/\s+/g, "-")}'`)
        .join(",\n");
    }
  }

  const entries = Object.entries(shapes)
    .map(([key, svg]) => `\t'${key}': ${JSON.stringify(svg)}`)
    .join(",\n\n");

  const output = `// shapeDefs.js — AUTO-GENERATED by fetch-assets.js
// Do not edit manually. Rebuild by running: npm run fetch-assets
// Sources: src/mandala/assets/shapes/

export const shapeDefs = {
${entries}
};

// Map figure choice strings to shape def IDs
export const figureShapeMap = {
${figureMapEntries}
};
`;

  writeFileSync(SHAPE_DEFS_OUT, output, "utf-8");
  console.log(`  ✓ Rebuilt shapeDefs.js (${Object.keys(shapes).length} shapes)`);
}

console.log(`\n[fetch-assets] mode=${mode}`);

if (mode === "local") {
  fetchLocal();
} else if (mode === "s3") {
  fetchS3();
} else {
  console.error(`  ✗ Unknown ASSETS_SOURCE="${mode}". Use "local" or "s3".`);
  process.exit(1);
}

// Rebuild shapeDefs from the freshly copied assets
rebuildShapeDefs().catch((err) => {
  console.error("  ✗ Failed to rebuild shapeDefs:", err);
  process.exit(1);
});
